-- Departments Table
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Positions Table
CREATE TABLE IF NOT EXISTS positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    level INTEGER DEFAULT 1, -- 1: Staff, 2: Supervisor, 3: Manager
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Holidays Table
CREATE TABLE IF NOT EXISTS holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Update Employees Table
ALTER TABLE employees ADD COLUMN IF NOT EXISTS department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS position_id BIGINT REFERENCES positions(id) ON DELETE SET NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS leave_quota INTEGER DEFAULT 12;

-- Update Leaves Table for Approval Workflow
-- IMPORTANTE: employees.id is TEXT, so approver_id must be TEXT
ALTER TABLE leaves ADD COLUMN IF NOT EXISTS approver_id TEXT REFERENCES employees(id);
ALTER TABLE leaves ADD COLUMN IF NOT EXISTS rejection_reason TEXT;

-- RLS & Policies for New Tables
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE holidays ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow Public Access" ON departments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow Public Access" ON positions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow Public Access" ON holidays FOR ALL USING (true) WITH CHECK (true);
